#!/sbin/openrc-run

description="Kokoro FastAPI (CPU)"

command="/usr/bin/uvicorn"
command_args="kokoro_fastapi.main:app --host 0.0.0.0 --port 8880"
command_user="kokoro-fastapi:kokoro-fastapi"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

export USE_GPU=false
export USE_ONNX=false
export MODEL_DIR=/var/lib/kokoro-fastapi/models
export VOICES_DIR=/var/lib/kokoro-fastapi/voices/v1_0
export WEB_PLAYER_PATH=/var/lib/kokoro-fastapi/web

depend() {
	need net
}
