updates:
  - cooldown:
      default-days: 7
    directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
  - cooldown:
      default-days: 7
    directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly
version: 2
