# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.14.0

EAPI=8

inherit go-module

DESCRIPTION="Netplay server for N64 emulators."
HOMEPAGE="https://github.com/gopher64/gopher64-netplay-server"
SRC_URI="https://github.com/gopher64/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/Tatsh/tatsh-overlay/releases/download/__distfiles__/${P}-vendor.tar.xz
"
LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64"
RESTRICT="mirror"

DOCS=( README.md )

src_compile() {
	env CGO_ENABLED=0 go build -a -o "${PN}" || die
}

src_install() {
	dobin "${PN}"
	einstalldocs
}
