#!/usr/bin/php
<?php
/**
 * Waits and compiles JavaScript files (Gentoo version).
 *
 * @copyright Copyright (c) 2011 Poluza.
 * @author Andrew Udvare [au] <andrew@poluza.com>
 * @license Proprietary.
 *
 * @package SutraScripts
 * @link http://www.example.com/
 *
 * @version 1.0
 */

$php_is_first = substr(strtolower($argv[0]), 0, 3) === 'php';

if ($php_is_first && $argc != 3) {
  printf('USAGE: php %s SITE_ROOT'."\n", $argv[1]);
  exit(1);
}
else if ($argc != 2) {
  printf('USAGE: %s SITE_ROOT'."\n", $argv[0]);
  exit(1);
}

$root = $php_is_first ? realpath($argv[2]) : realpath($argv[1]);
if (!is_readable($root.'/global.php')) {
  print 'Not a valid root directory.'."\n";
  exit(1);
}

chdir($root);
require './global.php';

sDatabase::getInstance();

try {
  require '/usr/share/php/sutra/scripts/compile-javascript.inc';
}
catch (fUnexpectedException $e) {
  print $e->getMessage()."\n";
  exit(1);
}

for (;;) {
  try {
    $records = fRecordSet::build('CompiledJavascriptFile', array('completed=' => FALSE), array('date_created' => 'desc'), 1);
    $records->tossIfEmpty();

    $record = $records->getRecord(0);
    $filename = $record->getFilename();
    $compiled = compileJavaScript();

    $ret = file_put_contents('./'.$record->getFilename(), $compiled, LOCK_EX);
    if ($ret === FALSE) {
      throw new fUnexpectedException('Could not write to file %s', $record->getFilename());
    }

    $record->setCompleted(TRUE);
    $record->store();
  }
  catch (fUnexpectedException $e) {
    $message = strip_tags($e->getMessage());
    $message = preg_replace("#\n+#", ' ', $message);
    fCore::debug($message."\n");
  }
  catch (fEmptySetException $e) {
    //fCore::debug('Nothing to compile.');
  }

  //fCore::debug('Sleeping for 30 seconds.');
  sleep(30);
}
