# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# CRATES generated by pycargoebuild 0.16.0
CRATES="
	arc-swap@1.9.2
	arrayvec@0.7.8
	async-channel@2.5.0
	async-task@4.7.1
	atomic-waker@1.1.2
	autocfg@1.5.1
	base64@0.23.1
	bitflags@1.3.2
	bitflags@2.13.1
	blocking@1.7.0
	bytemuck@1.25.2
	byteorder@1.5.0
	bytes@1.12.1
	cfg-if@1.0.4
	chfft@0.3.4
	concurrent-queue@2.5.0
	crc32fast@1.5.1
	crossbeam-utils@0.8.22
	dasp_sample@0.11.0
	encoding_rs@0.8.35
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.2
	extended@0.1.0
	fastrand@2.5.0
	futures-channel@0.3.34
	futures-core@0.3.34
	futures-executor@0.3.34
	futures-io@0.3.34
	futures-lite@2.6.1
	futures-macro@0.3.34
	futures-sink@0.3.34
	futures-task@0.3.34
	futures-util@0.3.34
	futures@0.3.34
	getrandom@0.4.3
	heck@0.5.0
	itoa@1.0.18
	lazy_static@1.5.0
	libc@0.2.189
	linux-raw-sys@0.12.1
	log@0.4.34
	memchr@2.8.3
	num-bigint@0.4.8
	num-complex@0.4.6
	num-integer@0.1.47
	num-rational@0.4.2
	num-traits@0.2.19
	once_cell@1.21.4
	parking@2.2.1
	pin-project-lite@0.2.17
	piper@0.2.5
	portable-atomic@1.15.0
	proc-macro2@1.0.107
	pyo3-async-runtimes@0.29.0
	pyo3-build-config@0.29.2
	pyo3-ffi@0.29.2
	pyo3-log@0.13.4
	pyo3-macros-backend@0.29.2
	pyo3-macros@0.29.2
	pyo3@0.29.2
	quote@1.0.47
	r-efi@6.0.0
	rodio@0.22.2
	rustix@1.1.4
	rustversion@1.0.23
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_json@1.0.151
	slab@0.4.12
	symphonia-bundle-flac@0.5.5
	symphonia-bundle-mp3@0.5.5
	symphonia-codec-aac@0.5.5
	symphonia-codec-pcm@0.5.5
	symphonia-codec-vorbis@0.5.5
	symphonia-core@0.5.5
	symphonia-format-isomp4@0.5.5
	symphonia-format-ogg@0.5.5
	symphonia-format-riff@0.5.5
	symphonia-metadata@0.5.5
	symphonia-utils-xiph@0.5.5
	symphonia@0.5.5
	syn@2.0.119
	syn@3.0.3
	target-lexicon@0.13.5
	tempfile@3.27.0
	thiserror-impl@2.0.20
	thiserror@2.0.20
	tokio@1.53.1
	unicode-ident@1.0.24
	windows-link@0.2.1
	windows-sys@0.61.2
	zmij@1.0.23
"

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin
PYTHON_COMPAT=( python3_{10..15} )

inherit cargo distutils-r1 pypi

DESCRIPTION="Rust core for the shazamio Shazam API client."
HOMEPAGE="https://github.com/shazamio/shazamio-core
	https://pypi.org/project/shazamio-core/"
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD MIT MPL-2.0
	Unicode-3.0
"
SLOT="0"
KEYWORDS="~amd64"
