# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=setuptools
PYTHON_COMPAT=( python3_{11..14} )
inherit distutils-r1

DESCRIPTION="MIPS instruction decoder."
HOMEPAGE="https://github.com/Decompollaborate/rabbitizer"
SRC_URI="https://github.com/Decompollaborate/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.gh.tar.gz"

LICENSE="MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

python_prepare_all() {
	sed -re 's/"-Os", //' -i setup.py || die
	distutils-r1_python_prepare_all
}

distutils_enable_tests pytest
