# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

DISTUTILS_USE_PEP517=hatchling
PYTHON_COMPAT=( python3_{11..14} )
inherit distutils-r1 pypi

DESCRIPTION="MIPS instruction decoder."
HOMEPAGE="https://github.com/ethteck/splat"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
RESTRICT="test"

RDEPEND="dev-python/pyyaml[${PYTHON_USEDEP}]
	dev-python/pylibyaml[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/intervaltree[${PYTHON_USEDEP}]
	dev-python/colorama[${PYTHON_USEDEP}]
	dev-util/spimdisasm[${PYTHON_USEDEP}]
	dev-python/rabbitizer[${PYTHON_USEDEP}]
	dev-python/pygfxd[${PYTHON_USEDEP}]
	dev-python/n64img[${PYTHON_USEDEP}]
	dev-python/crunch64[${PYTHON_USEDEP}]"
