# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# Nothing here is built against a fixed Ghidra: the extension is compiled
# against whatever dev-util/ghidra is installed. The eclass requires the
# variable all the same.
GHIDRA_PV="12.1.3"
GHIDRA_EXT_NAME="GhidraExtensionManager"
# Ghidra 12 runs on Java 21.
JAVA_PKG_WANT_SOURCE="21"
JAVA_PKG_WANT_TARGET="21"

inherit java-utils-2 ghidra-extension

DESCRIPTION="Ghidra extension that installs and updates other Ghidra extensions."
HOMEPAGE="https://github.com/antoniovazquezblanco/GhidraExtensionManager"
SRC_URI="https://github.com/antoniovazquezblanco/${GHIDRA_EXT_NAME}/archive/refs/tags/v${PV}.tar.gz
	-> ${P}.tar.gz"
S="${WORKDIR}/${GHIDRA_EXT_NAME}-${PV}"

# Upstream ships no licence file and states no terms anywhere in the
# repository. The jars vendored in lib/ are Apache-2.0 (commons-io,
# commons-lang3, jackson-*) except github-api, which is MIT.
LICENSE="all-rights-reserved Apache-2.0 MIT"
KEYWORDS="~amd64"
RESTRICT="bindist mirror"

PATCHES=(
	"${FILESDIR}/${PN}-0.3.2-catalog-in-user-settings.patch"
	"${FILESDIR}/${PN}-0.3.2-no-self-update.patch"
)

src_prepare() {
	eapply "${PATCHES[@]}"
	ghidra-extension_src_prepare

	# Substituted by Ghidra's own Gradle plugin when it assembles an extension.
	# The version= placeholder is left to the eclass, which points it at the
	# installed Ghidra.
	sed -i "s/@extname@/${GHIDRA_EXT_NAME}/" extension.properties || die

	# Generated by the build.gradle task of the same name, from the git tag.
	cat > src/main/java/extensionmanager/ExtensionManagerVersion.java <<-EOF || die
		package extensionmanager;

		public class ExtensionManagerVersion {
		    public static final String GIT_VERSION = "v${PV}";
		}
	EOF
}

src_compile() {
	# Upstream builds with Gradle, which resolves Ghidra's jars and its own
	# dependencies over the network. Both are already on disk: Ghidra is
	# installed and the dependencies are vendored in lib/, so javac is enough.
	local classpath
	classpath="$(find "${ESYSROOT}${GHIDRA_HOME}" -name '*.jar' \
		-not -path '*/Ghidra/Extensions/*' -printf '%p:')" || die
	classpath+="$(printf '%s:' lib/*.jar)"

	local sources=()
	readarray -d '' sources < <(find src/main/java -name '*.java' -print0)
	ejavac -d classes -encoding UTF-8 -proc:none -classpath "${classpath}" "${sources[@]}"
	jar --create --file "lib/${GHIDRA_EXT_NAME}.jar" -C classes . || die

	# The whole directory is installed, and none of this belongs in it. The
	# eclass removes the Gradle files.
	rm -r classes doc src README.md || die

	ghidra-extension_src_compile
}

pkg_postinst() {
	elog "The catalog installed here is the snapshot upstream committed for this"
	elog "release, and it lists nothing for the newest Ghidra versions. Use"
	elog "\"Update catalog\" in the dialog to fetch the current one; it is kept"
	elog "in ~/.config/ghidra."
	elog ""
	elog "Extensions installed from the extension manager go into Ghidra's"
	elog "per-user directory, ~/.config/ghidra, not into this installation, and"
	elog "are not known to Portage. Prefer the packaged extensions in this"
	elog "overlay where one exists, since two copies of the same extension make"
	elog "Ghidra report a duplicate."
}
